blog/urls.py
from django.urls import path
from .views import BulletinListView, BulletinDetailView, MemberListView, MemberDetailView
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('bulletins/', BulletinListView.as_view(), name='bulletin_list'),
    path('bulletins/<int:pk>/', BulletinDetailView.as_view(), name='bulletin-detail'),
    path('members/', MemberListView.as_view(), name='member_list'),
    path('members/<int:pk>/', MemberDetailView.as_view(), name='member_detail'),
    path('upload/', views.BulletinUploadView.as_view(), name='bulletin_upload'),
    path('merge-pdfs/', views.merge_latest_pdfs, name='merge_pdfs'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth.decorators import user_passes_test

admin_site = user_passes_test(lambda u: u.is_superuser)(admin.site.urls)

urlpatterns = [      
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('review/', include('review.urls')),
    path('', include('basecamp.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "NewCovenant Administration"
admin.site.site_title = "NewCovenant Administration"
admin.site.index_title = "NewCovenant admin"
admin.site.block_title = "NewCovenant Admin"

handler400 = 'basecamp.views.custom_bad_request'
handler403 = 'basecamp.views.custom_forbidden'
handler404 = 'basecamp.views.custom_page_not_found'
handler500 = 'basecamp.views.custom_server_error'
handler502 = 'basecamp.views.custom_bad_gateway'
handler503 = 'basecamp.views.custom_under_maintenance'

review/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'review'

urlpatterns = [
    path('', views.PostList.as_view(), name="review"),
    path('create/', views.PostCreate.as_view(), name="review_create"),
    path('<int:pk>/', views.PostDetail.as_view(), name="post_detail"),
    path('<int:pk>/update/', views.PostUpdate.as_view(), name="post_update"),
    path('<int:pk>/new_comment/', views.CommentCreate.as_view(), name='new_comment'),
    path('comment/<int:pk>/update/', views.CommentUpdate.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDelete.as_view(), name='comment_delete'),
]

review/models.py
import datetime
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdown



class Post(models.Model):
    content = MarkdownxField()
    name = models.CharField(max_length=100, blank=False, null=True)
    title = models.CharField(max_length=100, blank=False, null=True)
    date = models.DateField(blank=True, null=True, default=datetime.date.today)
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return '/review/{}/'.format(self.pk)

    def get_update_url(self):
        return self.get_absolute_url() + 'update/'

    def get_markdown_content(self):
        return markdown(self.content)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = MarkdownxField()
    author = models.CharField(max_length=100, blank=True, null=True)    
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def get_markdown_content(self):
        return markdown(self.text)

    def get_absolute_url(self):
        return self.post.get_absolute_url() + '#comment-id-{}'.format(self.pk)

review/forms.py
from .models import Comment, Post
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('name', 'title', 'date', 'content')        
    
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['readonly'] = True
        self.fields['name'].initial = '김곤주 목사'  # 초기값 설정
        self.fields['date'].widget.attrs['class'] = 'datepicker' 

review/views.py
import datetime
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Post, Comment
from .forms import CommentForm, PostForm


class PostList(ListView):
    model = Post
    template_name = 'review/post_list.html'
    paginate_by = 7

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        context['post_count'] = Post.objects.all().count()

        user_name = None
        if self.request.user.is_authenticated:
            user_name = self.request.user.username  

        context['user_name'] = user_name
        context['search_error'] = self.request.session.get('search_error', None)

        return context
    

class PostDetail(DetailView):
    model = Post
    template_name = 'review/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_count'] = Post.objects.all().count()
        context['comment_form'] = CommentForm()

        user_name = None
        if self.request.user.is_authenticated:
            user_name = self.request.user.username  

        context['user_name'] = user_name

        return context
    

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'review/post_form.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['user_name'] = self.request.user.username
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user.username  
        post.name = self.request.user.username
        if not post.date:
            post.date = datetime.date.today()
        post.save()
        return redirect('review:post_detail', pk=post.pk)


class PostUpdate(UpdateView):
    model = Post
    template_name = 'review/post_form.html'
    fields = ['content', 'title', 'date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['user_name'] = self.request.user.username
        return context


class CommentCreate(View):
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        user_name = None
        if request.user.is_authenticated:
            user_name = request.user.username  

        comment_form = CommentForm()
        
        context = {
            'post': post,
            'user_name': user_name,
            'comment_form': comment_form,
        }

        return render(request, 'review/post_detail.html', context)

    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        user_name = None
        if request.user.is_authenticated:
            user_name = request.user.username  

        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = user_name
            comment.save()
            return redirect(post.get_absolute_url())  

        context = {
            'post': post,
            'user_name': user_name,
            'comment_form': comment_form,
        }
        return render(request, 'review/post_detail.html', context)


class CommentUpdate(UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'review/comment_form.html'

    def get_object(self, queryset=None):
        comment = super().get_object(queryset)        
        user_name = None

        if self.request.user.is_authenticated:
            user_name = self.request.user.username  

        if comment.author != user_name:
            raise PermissionDenied('No right to edit')

        return comment
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_name = None
        if self.request.user.is_authenticated:
            user_name = self.request.user.username  

        context['user_name'] = user_name
        return context

    def get_success_url(self):
        post = self.get_object().post
        return post.get_absolute_url() + '#comment-list'


class CommentDelete(DeleteView):
    model = Comment
    template_name = 'review/comment_confirm_delete.html'

    def get_object(self, queryset=None):
        comment = super().get_object(queryset)        
        user_name = None

        if self.request.user.is_authenticated:
            user_name = self.request.user.username  

        if comment.author != user_name:
            raise PermissionDenied('No right to delete Comment')

        return comment
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_name = None
        if self.request.user.is_authenticated:
            user_name = self.request.user.username  

        context['user_name'] = user_name
        return context

    def get_success_url(self):
        post = self.get_object().post
        return post.get_absolute_url() + '#comment-list'

review/templates/review/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />        
        <title>새언약교회</title>
        <meta name="application-name" content="새언약교회">
        <meta name="description" content="새언약교회는 호주 시드니 Chestser Hill에 있는 한인교회입니다" />
        <meta name="author" content="감승재 전도사" />
        <!-- SEO Meta Tags-->
        <meta name="description" content="">
        <meta name="keywords" content="">
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/basecamp/favi/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/basecamp/css/styles.css" rel="stylesheet" />
        <style>
            #mainNav {
              padding-top: 1rem;
              padding-bottom: 1rem;
              background-color: #5a6268 !important;
            }
            #subpages {
                margin-top: 4rem; 
            }
            a {
                color: #ad5207; /* Change this to any color you like */
            }
          </style>
    </head>
    <body id="page-top">
        {% include 'review/navbar.html' %}
        
        
        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="footer" style="background-color: #5a6268; padding-top: 4rem; padding-bottom: 4rem;" id="contact">
            <div class="container" style="padding-top: 0.5rem; padding-bottom: 1rem;">                
                <div class="row align-items-center">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="https://www.youtube.com" aria-label="Twitter" target="_blank"><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/peterkim1515" aria-label="Facebook" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" aria-label="Google" target="_blank"><i class="fas fa-map-marker-alt"></i></a>
                    </div>
                    <div class="col-lg-4"></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;"><a class="link-dark text-decoration-none hover-effect" href="sms:+61466386584">0466 386 584 </a>(담임목사 김곤주)</div>
                </div>
            </div>
            <div class="container" style="">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">이메일 주소: <a class="link-dark text-decoration-none hover-effect" href="mailto:suy.church@gmail.com">kkj1515@hotmail.com</a></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">교회주소: <a class="link-dark text-decoration-none me-3 hover-effect" 
                        href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" 
                        target="_blank">
                        109 Priam St, Chester Hill NSW 2162
                    </a></div>
                </div>
            </div>
            <div class="container" style="">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">사랑방주소: <a class="link-dark text-decoration-none me-3 hover-effect" 
                        href="https://www.google.com/maps?q=2/2+Amy+Street,+Regents+Park+NSW+2143" 
                        target="_blank">
                        2/2 Amy Street, Regents Park NSW 2143
                    </a></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">2024 All rights reserved &copy; 시드니 새언약교회</div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="{% static 'review/js/jquery.min.js' %}"></script>
        <script src="{% static 'review/js/bootstrap.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="/static/basecamp/js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>    
        <style>
            /* 링크 및 버튼 색상 변화 */
            .hover-effect {
                color: white; /* 기본 색상 */
                transition: color 0.3s, background-color 0.3s; /* 부드러운 전환 효과 */
            }
        
            .hover-effect:hover {
                color: #ffd700 !important/* 마우스를 올렸을 때 색상 */
                
            }
        </style>
        <script>
            function search_post() {
                var search_value = document.getElementById('search-input').value;    
                if (search_value.trim() === "") {
                    alert("Please enter a valid search term.");
                } else {
                    location.href = "/review/search/" + encodeURIComponent(search_value) + "/";
                }
            }    
            function wait_for_enterkey() {
                if (window.event.keyCode == 13) {
                    search_post();
                }
            }
        </script>
    </body>      
</html>

review/templates/review/base_sub.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />        
        <title>새언약교회</title>
        <meta name="application-name" content="새언약교회">
        <meta name="description" content="새언약교회는 호주 시드니 Chestser Hill에 있는 한인교회입니다" />
        <meta name="author" content="감승재 전도사" />
        <!-- SEO Meta Tags-->
        <meta name="description" content="">
        <meta name="keywords" content="">
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/basecamp/favi/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/basecamp/css/styles.css" rel="stylesheet" />
        <link href="/static/review/css/styles.css" rel="stylesheet" />
        <style>
            #mainNav {
              padding-top: 1rem;
              padding-bottom: 1rem;
              background-color: #5a6268 !important;
            }
            #subpages {
                margin-top: 4rem; 
            }
            a {
                color: #ad5207; /* Change this to any color you like */
            }
          </style>
    </head>
    <body id="page-top">
        {% include 'review/navbar_sub.html' %}
        
        
        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="footer" style="background-color: #5a6268; padding-top: 4rem; padding-bottom: 4rem;" id="contact">
            <div class="container" style="padding-top: 0.5rem; padding-bottom: 1rem;">                
                <div class="row align-items-center">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="https://www.youtube.com" aria-label="Twitter" target="_blank"><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/peterkim1515" aria-label="Facebook" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" aria-label="Google" target="_blank"><i class="fas fa-map-marker-alt"></i></a>
                    </div>
                    <div class="col-lg-4"></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;"><a class="link-dark text-decoration-none hover-effect" href="sms:+61466386584">0466 386 584 </a>(담임목사 김곤주)</div>
                </div>
            </div>
            <div class="container" style="">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">이메일 주소: <a class="link-dark text-decoration-none hover-effect" href="mailto:suy.church@gmail.com">kkj1515@hotmail.com</a></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">교회주소: <a class="link-dark text-decoration-none me-3 hover-effect" 
                        href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" 
                        target="_blank">
                        109 Priam St, Chester Hill NSW 2162
                    </a></div>
                </div>
            </div>
            <div class="container" style="">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">사랑방주소: <a class="link-dark text-decoration-none me-3 hover-effect" 
                        href="https://www.google.com/maps?q=2/2+Amy+Street,+Regents+Park+NSW+2143" 
                        target="_blank">
                        2/2 Amy Street, Regents Park NSW 2143
                    </a></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">2024 All rights reserved &copy; 시드니 새언약교회</div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/basecamp/js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>    
        <style>
            /* 링크 및 버튼 색상 변화 */
            .hover-effect {
                color: white; /* 기본 색상 */
                transition: color 0.3s, background-color 0.3s; /* 부드러운 전환 효과 */
            }
        
            .hover-effect:hover {
                color: #ffd700 !important/* 마우스를 올렸을 때 색상 */
                
            }
        </style>        
    </body>      
</html>

review/templates/review/comment_confirm_delete.html
{% extends 'review/base.html' %}

{% block title %} Confirm Deletion {% endblock %}

{% block content %}
    <h3>Delete Comment: </h3>
    <hr/>
    <form method="post">{% csrf_token %}
        {{ object.get_markdown_content | safe }}
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>

    {{ form.media }}
{% endblock %}

review/templates/review/comment_form.html
{% extends 'review/base.html' %}

{% block title %} EasyGo Reveiws {% endblock %}

{% block content %}
    <h3>Edit Comment: </h3>
    <hr/>
    <form method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>

    {{ form.media }}
{% endblock %}

review/templates/review/post_detail.html
{% extends 'review/base_sub.html' %}

{% block content %}
<br>
<div class="container review-section" style="padding: 20px; margin-bottom: 20px;">  
    <br/><br><br>
    <!-- Author -->
    <div class="low" style="display: flex; align-items: center; ">
        <div><br>
            <span style="color: #3E2723; font-weight: bold;">{{ object.title }}</span>            
            <span style="margin-left: 10px; ">posted on {{ object.date }}</span>
        </div>
        
        {% if user_name == object.name %}
            <button type="button" class="btn btn-primary" style="margin-left: auto;" onclick="location.href='{{ object.get_update_url }}'">EDIT REVIEW</button>
        {% endif %}
    </div>
    <br><br>    
    <!-- Post Content -->
    {{ object.get_markdown_content | safe }}

    <hr>

    <!-- Comments Form -->
    <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
            {% if not email %}
            <button type="button" class="btn btn-outline-success btn-block" data-toggle="modal" data-target="#loginModal">
                Log in
            </button>            
            {% else %}
            <form method="post" action="{{ object.get_absolute_url }}new_comment/">{% csrf_token %}
                <div class="form-group">
                    {{ comment_form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary btn-sm float-right">Submit Comment</button>                
            </form>
            {% endif %}
        </div>
    </div>

    <div id="comment-list">
        {% for comment in object.comment_set.all %}
            <div class="media mb-4" id="comment-id-{{ comment.pk }}">                
                <div class="media-body">
                    {% if comment.author == user_name %}
                        <button class="btn btn-sm btn-info float-right" onclick="location.href='/review/comment/{{ comment.pk }}/update/'">edit</button>
                        <button class="btn btn-sm btn-warning float-right" data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">delete</button>
                    {% endif %}
                    <h5 class="mt-0">{{ comment.author }} <small class="text-muted">{{ comment.created_at }}</small></h5>
                    {{ comment.get_markdown_content | safe }}
                </div>
            </div>
        {% endfor %}
    </div>

    {% for comment in object.comment_set.all %}
        {% if user_name == comment.author %}
            <!-- Modal -->
            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">정말로 삭제하시겠습니까?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>{{ comment.get_markdown_content | safe  }}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" onclick="location.href='/review/comment/{{ comment.pk }}/delete/'">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

review/templates/review/post_list.html
{% extends 'review/base.html' %}

{% block content %}
<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h3>설교문 및 칼럼</h3>
        </div>
        {% if user.is_authenticated %}
            <div class="d-flex justify-content-end mb-3">
                <a href="{% url 'review:review_create' %}" class="btn btn-success">글쓰기</a>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-12" id="main-div">
                <br/>                
                <br/>
                {% if object_list %}
                    {% for post in object_list %}
                        <div class="card mb-4" id="post-card-{{ post.pk }}">
                            <div class="card-header text-muted">
                                Title: {{ post.title }} &nbsp;&nbsp;posted by {{ post.name }}&nbsp;&nbsp;&nbsp;{{ post.date }}
                            </div>
                            <div class="card-body">
                                <p class="card-text">{{ post.get_markdown_content|striptags|safe|truncatewords:50 }}</p>
                                <br/>
                                {% if post.name %}
                                    <p class="card-text">
                                        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary" id="read-more-post-{{ post.pk }}">Read More &rarr;</a>
                                    </p>
                                {% endif %}
                            </div>                            
                        </div>
                    {% endfor %}

                    {% if is_paginated %}
                        <ul class="pagination justify-content-center mb-4">
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr; Older</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#">&larr; Older</a>
                                </li>
                            {% endif %}

                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer &rarr;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#">Newer &rarr;</a>
                                </li>
                            {% endif %}
                        </ul>
                    {% endif %}
                {% else %}
                    <h5>No Post</h5>
                {% endif %}
            </div>

            <!-- <div class="col-md-3" id="side-div">
                <h5 class="side-h"><br/></h5>
                <h5 class="side-h"><br/></h5>
                
                <div class="search-widget">                    
                    <div class="input-group">
                        <input type="text" id="search-input" onkeyup="wait_for_enterkey()" class="form-control" placeholder="단어로 찾으세요..."/>
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="button" onclick="search_post();">검색 !</button>
                        </span>
                    </div>
                    <div id="error-message" class="text-danger mt-2" style="display: none;"></div>                    
                </div>
                
                {% if search_error %}
                    <script>
                        alert("{{ search_error|escapejs }}");
                    </script>
                {% endif %}
            </div> -->
        </div>
    </div>
</section>


{% endblock %}