basecamp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "basecamp"

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),    
    path('introduction/', views.introduction, name='introduction'),
    path('bulletin_list/', views.bulletin_list, name='bulletin_list'),  
    path('meetings/', views.meetings, name='meetings'),   
    path('workers/', views.workers, name='workers'), 
    path('column/', views.column, name='column'),
    path('location/', views.location, name='location'),
    path('worship_music/', views.worship_music, name='worship_music'),
    path('protected/contact_list', views.serve_pdf, name='contact_list'), 
] 

urlpatterns += static('/media/', document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import BulletinListView, BulletinDetailView, MemberListView, MemberDetailView
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('bulletins/', BulletinListView.as_view(), name='bulletin_list'),
    path('bulletins/<int:pk>/', BulletinDetailView.as_view(), name='bulletin-detail'),
    path('members/', MemberListView.as_view(), name='member_list'),
    path('members/<int:pk>/', MemberDetailView.as_view(), name='member_detail'),
    path('upload/', views.BulletinUploadView.as_view(), name='bulletin_upload'),
    path('merge-pdfs/', views.merge_latest_pdfs, name='merge_pdfs'),
]

gallery/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'gallery'

urlpatterns = [
    path('', views.GalleryList.as_view(), name="gallery"),
    path('create/', views.GalleryCreate.as_view(), name="gallery_create"),
    path('<int:pk>/', views.GalleryDetail.as_view(), name="gallery_detail"),
    path('<int:pk>/update/', views.GalleryUpdate.as_view(), name="gallery_update"),
    
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth.decorators import user_passes_test

admin_site = user_passes_test(lambda u: u.is_superuser)(admin.site.urls)

urlpatterns = [      
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('review/', include('review.urls')),
    path('', include('basecamp.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "NewCovenant Administration"
admin.site.site_title = "NewCovenant Administration"
admin.site.index_title = "NewCovenant admin"
admin.site.block_title = "NewCovenant Admin"

handler400 = 'basecamp.views.custom_bad_request'
handler403 = 'basecamp.views.custom_forbidden'
handler404 = 'basecamp.views.custom_page_not_found'
handler500 = 'basecamp.views.custom_server_error'
handler502 = 'basecamp.views.custom_bad_gateway'
handler503 = 'basecamp.views.custom_under_maintenance'

gallery/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from markdownx.utils import markdown


class Gallery(models.Model):
    title = models.CharField(max_length=250)
    date = models.DateField(blank=True, null=True, default=datetime.date.today)
    head_image = models.ImageField(upload_to='gallery/%Y/%m/%d/', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=100, blank=True, null=True)
    
    class Meta:
        ordering = ['-created', ]

    def __str__(self):
        return '{}'.format(self.title)

    def get_absolute_url(self):
        return '/gallery/{}/'.format(self.pk)

    def get_update_url(self):
        return self.get_absolute_url() + 'update/'

gallery/forms.py
from .models import Gallery
from django import forms


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ('title', 'date', 'author', 'head_image')        
    
    def __init__(self, *args, **kwargs):
        super(GalleryForm, self).__init__(*args, **kwargs)
        self.fields['date'].widget.attrs['class'] = 'datepicker' 

        # 'author' 필드를 초기값으로 로그인한 사용자의 username을 설정
        # if 'author' not in self.initial:
        #     self.initial['author'] = kwargs.get('initial', {}).get('author', None)

basecamp/views.py
import os
from django.shortcuts import render, redirect
from django.http import FileResponse, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.conf import settings


def index(request): return redirect('/home/')


def home(request): return render(request, 'basecamp/home.html')


def introduction(request):     
    return render(request, 'basecamp/introduction.html')


def bulletin_list(request):     
    return render(request, 'basecamp/bulletin_list.html')


def meetings(request):     
    return render(request, 'basecamp/meetings.html')


def sitemap(request): 
    return render(request, 'basecamp/sitemap.xml')


def workers(request): 
    return render(request, 'basecamp/workers.html')


def column(request):
    return render(request, 'basecamp/column.html')


def location(request):
    return render(request, 'basecamp/location.html')


def worship_music(request):
    return render(request, 'basecamp/worship_music.html')


@login_required
def serve_pdf(request):
    pdf_path = os.path.join(settings.MEDIA_ROOT, 'protected', 'contact_list.pdf')
    try:
        return FileResponse(open(pdf_path, 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        return render(request, '404.html', status=404)
    

from django.shortcuts import render


# error handler 400 403 404 500 502 503 
def custom_bad_request(request, exception):
    return render(request, '400.html', status=400)


def custom_forbidden(request, exception):
    return render(request, '403.html', status=403)


def custom_page_not_found(request, exception):
    return render(request, '404.html', status=404)


def custom_server_error(request):
    return render(request, '500.html', status=500)


def custom_bad_gateway(request):
    return render(request, '502.html', status=502)


def custom_under_maintenance(request):
    return render(request, '503.html', status=503)

gallery/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Gallery
from .forms import GalleryForm


class GalleryList(ListView):
    model = Gallery
    template_name = 'gallery/gallery_list.html'
    paginate_by = 7

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gallery_count'] = Gallery.objects.all().count()
        context['user_name'] = self.request.user.username
        context['search_error'] = self.request.session.get('search_error', None)
        return context


class GalleryCreate(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = GalleryForm(initial={'name': request.user.username})
        return render(request, 'gallery/gallery_form.html', {'form': form, 'form_guide': 'Please upload your gallery'})

    def post(self, request, *args, **kwargs):
        form = GalleryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/gallery/')
        return render(request, 'gallery/gallery_form.html', {'form': form, 'form_guide': 'Please upload your gallery'})


class GalleryDetail(DetailView):
    model = Gallery
    template_name = 'gallery/gallery_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gallery_count'] = Gallery.objects.all().count()
        user_name = self.request.user.username
        context['user_name'] = user_name
        return context


class GalleryUpdate(LoginRequiredMixin, UpdateView):
    model = Gallery
    template_name = 'gallery/gallery_form.html'
    fields = ['date', 'title']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_name = self.request.user.username
        context['user_name'] = user_name
        return context


def index(request):
    Gallerys = Gallery.objects.all()
    return render(request, 'gallery/index.html', {'Gallerys': Gallerys})

basecamp/templates/basecamp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />        
        <title>새언약교회</title>
        <meta name="application-name" content="새언약교회">
        <meta name="description" content="새언약교회는 호주 시드니 Chestser Hill에 있는 한인교회입니다" />
        <meta name="author" content="감승재 전도사" />
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/basecamp/favi/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/basecamp/css/styles.css" rel="stylesheet" />
        <style>
            #mainNav {
              padding-top: 1rem;
              padding-bottom: 1rem;
              background-color: #5a6268 !important;
            }
            #subpages {
                margin-top: 4rem; 
            }
            a {
                color: #ad5207; /* Change this to any color you like */
            }
          </style>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="/home"><img src="{% static 'basecamp/assets/img/favicon.png' %}" alt="파비콘" class="favicon-img" /><span class="logo-text">새언약교회</span></a>
                <a class="btn btn-dark btn-social mx-2" href="https://www.youtube.com" aria-label="Twitter" target="_blank"><i class="fab fa-youtube"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/peterkim1515" aria-label="Facebook" target="_blank"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" aria-label="Google" target="_blank"><i class="fas fa-map-marker-alt"></i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/home/">Home</a>
                        </li>
                        <!-- 교회소개 드롭다운 메뉴 -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown">
                                교회안내
                            </a>
                            <ul class="dropdown-menu" >
                                <li><a class="dropdown-item" href="/home/#about">교회소개</a></li>
                                <li><a class="dropdown-item" href="/introduction">목사님소개</a></li>
                                <li><a class="dropdown-item" href="/workers">섬기는 사람들</a></li>
                                <li><a class="dropdown-item" href="/location">교회위치 및 연락처</a></li>
                                <li><a class="dropdown-item" href="/pickup">픽업정보 및 온라인헌금</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown">
                                예배안내
                            </a>
                            <ul class="dropdown-menu" >
                                <li><a class="dropdown-item" href="/meetings">예배와 모임</a></li>
                                <li><a class="dropdown-item" href="/blog/bulletins">교회주보</a></li>
                                <li><a class="dropdown-item" href="/worship_music">찬양악보</a></li>
                                <li><a class="dropdown-item" href="{% url 'basecamp:contact_list' %}" target="_blank">장년부 교인연락처</a></li>
                            </ul>
                        </li>     
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown">
                                하나님의 말씀
                            </a>
                            <ul class="dropdown-menu" >
                                <li><a class="dropdown-item" href="/home/#words">주일설교</a></li>
                                <li><a class="dropdown-item" href="/review">목사님 칼럼</a></li>
                            </ul>
                        </li>                             
                        <!-- <li class="nav-item"><a class="nav-link" href="/gallery">갤러리</a></li>                         -->
                    </ul>
                </div>
            </div>
        </nav>
        
        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="footer" style="background-color: #5a6268; padding-top: 4rem; padding-bottom: 4rem;" id="contact">
            <div class="container" style="padding-top: 0.5rem; padding-bottom: 1rem;">                
                <div class="row align-items-center">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="https://www.youtube.com" aria-label="Twitter" target="_blank"><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/peterkim1515" aria-label="Facebook" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" aria-label="Google" target="_blank"><i class="fas fa-map-marker-alt"></i></a>
                    </div>
                    <div class="col-lg-4"></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;"><a class="link-dark text-decoration-none hover-effect" href="sms:+61466386584">0466 386 584 </a>(담임목사 김곤주)</div>
                </div>
            </div>
            <div class="container" style="">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">이메일 주소: <a class="link-dark text-decoration-none hover-effect" href="mailto:suy.church@gmail.com">kkj1515@hotmail.com</a></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">교회주소: <a class="link-dark text-decoration-none me-3 hover-effect" 
                        href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" 
                        target="_blank">
                        109 Priam St, Chester Hill NSW 2162
                    </a></div>
                </div>
            </div>
            <div class="container" style="">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">사랑방주소: <a class="link-dark text-decoration-none me-3 hover-effect" 
                        href="https://www.google.com/maps?q=2/2+Amy+Street,+Regents+Park+NSW+2143" 
                        target="_blank">
                        2/2 Amy Street, Regents Park NSW 2143
                    </a></div>
                </div>
            </div>
            <div class="container" style="padding-top: 1rem;">                
                <div class="row align-items-center">                    
                    <div class="col-12 text-center" style="color: white;">2024 All rights reserved &copy; 시드니 새언약교회</div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/basecamp/js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>    
        <style>
            /* 링크 및 버튼 색상 변화 */
            .hover-effect {
                color: white; /* 기본 색상 */
                transition: color 0.3s, background-color 0.3s; /* 부드러운 전환 효과 */
            }
        
            .hover-effect:hover {
                color: #ffd700 !important/* 마우스를 올렸을 때 색상 */
                
            }
        </style>
    </body>      
</html>

basecamp/templates/basecamp/church_bulletin.html
{% extends 'basecamp/base.html' %}
{% load static %}

{% block content %}
<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h3>교회 주보</h3>
        </div>
        <div class="bulletin_list mt-4">
            {% for bulletin in bulletins %}
                <div class="bulletin-item">
                    <h5>{{ bulletin.title }}</h5>
                    <p>날짜: {{ bulletin.date|date:"Y년 m월 d일" }}</p>
                    {% if bulletin.pdf_file %}
                        <a href="{{ bulletin.pdf_file.url }}" target="_blank" class="btn btn-primary">주보 보기</a>
                    {% else %}
                        <p class="text-danger">PDF 파일이 없습니다.</p>
                    {% endif %}
                </div>
                <hr>
            {% empty %}
                <p>등록된 주보가 없습니다.</p>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

basecamp/templates/basecamp/column.html
{% extends 'basecamp/base.html' %}
{% load static %}

{% block content %}
<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h3>목사님 칼럼 페이지가 곧 만들어집니다</h3>
        </div>        
    </div>
</section>

{% endblock %}

basecamp/templates/basecamp/contact_list.html
{% extends 'basecamp/base.html' %}
{% load static %}

{% block content %}
<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h3>새언약 교회 장년부 연락처에 관하여 페이지를 구상중에 있습니다</h3>
        </div>        
    </div>
</section>

{% endblock %}

basecamp/templates/basecamp/gallery.html
{% extends 'basecamp/base.html' %}
{% load static %}

{% block content %}
<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h3>갤러리 페이지가 곧 오픈예정입니다</h3>
        </div>        
    </div>
</section>

{% endblock %}

basecamp/templates/basecamp/introduction.html
{% extends 'basecamp/base.html' %}
{% load static %}

{% block content %}

<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase" style="font-size: 2rem;">담임목사님 소개</h2>
            <h3 class="section-subheading text-muted">지혜와 사랑으로 이끄시는 목사님</h3>
        </div>
        <div class="row mb-4 pb-4">
            <!-- 왼쪽 섹션 -->
            <div class="col-lg-3 text-center">
                <img src="{% static 'basecamp/assets/img/team/profile1.webp' %}" alt="김곤주 목사" class="img-fluid mb-3">                
                <p class="text-muted" style="font-size: 1rem;">
                    김곤주 목사는 한국에서 학부와 신대원 그리고 강도사를 거쳐 목사 안수를 받기까지 
                    한국에서 10여년 이상 부교역자로 사역을 하였습니다.
                </p>
                <p class="text-muted" style="font-size: 1rem;">
                    호주에서 유학생활 및 이민생활을 시작하면서 호주 신학교에서 신학공부를 계속하였고, 
                    새언약 교회를 개척하여 섬기고 있습니다.
                </p>
                <p class="text-muted text-left" style="font-size: 0.9rem; margin-left: 0; padding-left: 0; display: inline-block; text-align: left;">
                    • 안양대 및 안양대 신대원 졸 (BA, M.Div)<br>
                    • 호주 몰링(Morling) 신대원 졸 (MA in Th)<br>
                    • 무어(Moore) 신대원 졸 (MA in Th)<br>
                    • 알파크루시스(Alphacrusis) 신대원 졸 (MTh 및 MPh)
                </p>         
            </div>
            <div class="col-lg-1"></div>
            <!-- 오른쪽 섹션 -->
            <div class="col-lg-7">                
                <p>
                    김곤주 목사님은 모든 성도가 하나님의 말씀을 통해 성장하여 온전한 그리스도의 몸으로 세워지기를 지향하며, 
                    그런 하나님의 나라가 확장되기를 소망하십니다.
                </p>
                <p>
                    또한, 두 군데 신학교에서 강의하시고 계시며 평생을 목회와 신학에 인생을 바치신 
                    하나님이 쓰시는 목회자요 신학자이십니다.
                </p>
                <p>
                    목사님 저서로는 <em>'원문 중심의 이야기 로마서'</em>와 <em>'바른 해석과 바른 신앙'</em>이 있습니다.
                </p>
                <br><br>
                <!-- 책 이미지 섹션 -->
                <div class="row">
                    <div class="col-md-6 text-center">
                        <img src="{% static 'basecamp/assets/img/book1.webp' %}" alt="원문 중심의 이야기 로마서" class="img-fluid w-75 shadow-sm mb-2">
                        <p class="text-muted" style="font-size: 0.9rem;"><em>원문 중심의 이야기 로마서</em></p>
                    </div>
                    <div class="col-md-6 text-center">
                        <img src="{% static 'basecamp/assets/img/book2.webp' %}" alt="바른 해석과 바른 신앙" class="img-fluid w-75 shadow-sm mb-2">
                        <p class="text-muted" style="font-size: 0.9rem;"><em>바른 해석과 바른 신앙</em></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

basecamp/templates/basecamp/location.html
{% extends 'basecamp/base.html' %}
{% load static %}

{% block content %}
<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h3>교회, 사랑방 위치에 관하여 페이지를 만들고 있습니다</h3>
        </div>        
    </div>
</section>

{% endblock %}

basecamp/templates/basecamp/meetings.html
{% extends 'basecamp/base.html' %}
{% block content %}
<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">예배와 모임</h2>
            <h3 class="section-subheading text-muted">건강한 교회, 성숙한 교회, 섬기는 교회</h3>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered table-striped text-center">
                    <thead class="thead-dark">
                        <tr>
                            <th>모임</th>
                            <th>요일</th>
                            <th>시간</th>
                            <th>장소</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>주일예배</td>
                            <td>주일</td>
                            <td>12:30 pm</td>
                            <td>
                                <a href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" target="_blank" rel="noopener noreferrer">
                                    Chester Hill 교회
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>중보기도회</td>
                            <td>주일</td>
                            <td>11:00 am</td>
                            <td>
                                <a href="https://www.google.com/maps?q=2/2+Amy+Street,+Regents+Park+NSW+2143" target="_blank" rel="noopener noreferrer">
                                    Regents Park 사랑방
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>수요성경공부</td>
                            <td>수요일</td>
                            <td>11:00 am</td>
                            <td>
                                <a href="https://www.google.com/maps?q=2/2+Amy+Street,+Regents+Park+NSW+2143" target="_blank" rel="noopener noreferrer">
                                    Regents Park 사랑방
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>주일학교</td>
                            <td>주일</td>
                            <td>3:00 pm</td>
                            <td>
                                <a href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" target="_blank" rel="noopener noreferrer">
                                    Chester Hill 교회
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>학생부</td>
                            <td>주일</td>
                            <td>3:00 pm</td>
                            <td>
                                <a href="https://www.google.com/maps/search/?api=1&query=109+Priam+St,+Chester+Hill" target="_blank" rel="noopener noreferrer">
                                    Chester Hill 교회
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>금요성경공부</td>
                            <td>금요일</td>
                            <td>11:00 am</td>
                            <td>
                                <a href="https://www.google.com/maps?q=2/2+Amy+Street,+Regents+Park+NSW+2143" target="_blank" rel="noopener noreferrer">
                                    Regents Park 사랑방
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>영어성경/회화</td>
                            <td>화요일</td>
                            <td>11:00 am</td>
                            <td>
                                <a href="https://www.google.com/maps?q=2/2+Amy+Street,+Regents+Park+NSW+2143" target="_blank" rel="noopener noreferrer">
                                    Regents Park 사랑방
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>신앙상담</td>
                            <td>금요일</td>
                            <td>2:00 pm</td>
                            <td>예약 후 정해진 장소</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock %}

basecamp/templates/basecamp/pickup.html
{% extends 'basecamp/base.html' %}
{% load static %}

{% block content %}
<section class="page-section" id="subpages">
    <div class="container">
        <div class="text-center">
            <h3>픽업에 관한 정보와 온라인 헌금에 관하여 페이지를 구상중에 있습니다</h3>
        </div>        
    </div>
</section>

{% endblock %}

basecamp/templates/basecamp/worship_music.html
<h2>찬양 악보를 만들어 어디서나 모발폰으로 볼 수 있게 만들겠습니다 ^^</h2>