blog/urls.py
from django.urls import path
from .views import BulletinListView, BulletinDetailView, MemberListView, MemberDetailView
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('bulletins/', BulletinListView.as_view(), name='bulletin_list'),
    path('bulletins/<int:pk>/', BulletinDetailView.as_view(), name='bulletin-detail'),
    path('members/', MemberListView.as_view(), name='member_list'),
    path('members/<int:pk>/', MemberDetailView.as_view(), name='member_detail'),
    path('upload/', views.BulletinUploadView.as_view(), name='bulletin_upload'),
    path('merge-pdfs/', views.merge_latest_pdfs, name='merge_pdfs'),
]

easygo_review/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'easygo_review'

urlpatterns = [
    path('', views.PostList.as_view(), name="easygo_review"),
    path('create/', views.PostCreate.as_view(), name="easygo_review_create"),
    path('custom_login/', views.custom_login_view, name='custom_login'),
    path('custom_logout/', views.custom_logout_view, name='custom_logout'),
    path('search/<str:q>/', views.PostSearch.as_view(), name="post_search"),
    path('<int:pk>/', views.PostDetail.as_view(), name="post_detail"),
    path('<int:pk>/update/', views.PostUpdate.as_view(), name="post_update"),
    path('<int:pk>/new_comment/', views.CommentCreate.as_view(), name='new_comment'),
    path('comment/<int:pk>/update/', views.CommentUpdate.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDelete.as_view(), name='comment_delete'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth.decorators import user_passes_test

admin_site = user_passes_test(lambda u: u.is_superuser)(admin.site.urls)

urlpatterns = [      
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('review/', include('review.urls')),
    path('', include('basecamp.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "NewCovenant Administration"
admin.site.site_title = "NewCovenant Administration"
admin.site.index_title = "NewCovenant admin"
admin.site.block_title = "NewCovenant Admin"

handler400 = 'basecamp.views.custom_bad_request'
handler403 = 'basecamp.views.custom_forbidden'
handler404 = 'basecamp.views.custom_page_not_found'
handler500 = 'basecamp.views.custom_server_error'
handler502 = 'basecamp.views.custom_bad_gateway'
handler503 = 'basecamp.views.custom_under_maintenance'

easygo_review/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import datetime


class Post(models.Model):
    content = MarkdownxField()
    name = models.CharField(max_length=100, blank=False, null=True)
    date = models.DateField(blank=True, null=True, default=datetime.date.today)
    rating = models.IntegerField(default=5, choices=[(i, i) for i in range(1, 6)])
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return str(self.author)

    def get_absolute_url(self):
        return '/easygo_review/{}/'.format(self.pk)

    def get_update_url(self):
        return self.get_absolute_url() + 'update/'

    def get_markdown_content(self):
        return markdown(self.content)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = MarkdownxField()
    author = models.CharField(max_length=100, blank=True, null=True)    
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_markdown_content(self):
        return markdown(self.text)

    def get_absolute_url(self):
        return self.post.get_absolute_url() + '#comment-id-{}'.format(self.pk)

easygo_review/forms.py
from .models import Comment, Post
from django import forms


class EmailLoginForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=254)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('name', 'content', 'rating')
        widgets = {
            'rating': forms.HiddenInput(),
            }
    
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['readonly'] = True

easygo_review/views.py
import json
import requests

from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.http import JsonResponse

from .models import Post, Comment
from .forms import CommentForm, PostForm
from blog.models import Post as BlogPost
from main.settings import RECIPIENT_EMAIL


def custom_login_view(request):
    error = None
    if request.method == 'POST':
        email = request.POST['email']
        posts = BlogPost.objects.filter(email=email)
        if posts.exists():
            post = posts.first()  
            request.session['email'] = post.email
            return redirect('easygo_review:easygo_review')
        else:
            error = 'This is not the email address in our system'
    return render(request, 'easygo_review/custom_login.html', {'error': error})


def custom_logout_view(request):
    request.session.flush()    
    return redirect('easygo_review:easygo_review')


def get_authenticated_post(request):
    email = request.session.get('email')
    if email:
        posts = BlogPost.objects.filter(email=email)
        if posts.exists():
            return posts.first()  
    return None


class PostList(ListView):
    model = Post
    template_name = 'easygo_review/post_list.html'
    paginate_by = 7

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        context['post_count'] = Post.objects.all().count()

        for post in context['object_list']:
            if post.rating is None:
                post.rating = 5

        # send_notice_email.delay('reviews accessed', 'reviews accessed', RECIPIENT_EMAIL)

        authenticated_post = get_authenticated_post(self.request)
        context['authenticated_post'] = authenticated_post 

        email = self.request.session.get('email', None)
        if email:
            blog_post = BlogPost.objects.filter(email=email).first()  
            if blog_post:
                user_name = blog_post.name
                context['user_name'] = user_name
            else:
                context['user_name'] = None
        else:
            context['user_name'] = None

        context['email'] = email 
        context['search_error'] = self.request.session.get('search_error', None)  

        return context
    

class PostCreate(View):
    def get(self, request, *args, **kwargs):
        email = request.session.get('email')  
        if email:
            blog_post = BlogPost.objects.filter(email=email).first()
            form = PostForm(initial={'name': blog_post.name})  
        else:
            form = PostForm()
        return render(request, 'easygo_review/post_form.html', {'form': form, 'form_guide': 'Please post your review'})

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)
        if form.is_valid():
            email = request.session.get('email')  
            if email:
                blog_post = BlogPost.objects.filter(email=email).first()
                form.instance.author = blog_post.name  
                form.instance.name = blog_post.name  
                rating = form.cleaned_data.get('rating')
                if not (1 <= rating <= 5):
                    form.add_error('rating', 'Rating must be between 1 and 5')
                    return render(request, 'easygo_review/post_form.html', {'form': form, 'form_guide': 'Please post your review'})
                form.save()

                return redirect('/easygo_review/')
        return render(request, 'easygo_review/post_form.html', {'form': form, 'form_guide': 'Please post your review'})
    

class PostSearch(PostList):
    def get_queryset(self):
        q = self.kwargs['q']
        object_list = Post.objects.filter(Q(name__contains=q) | Q(content__contains=q)) 
        return object_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data(object_list=object_list, **kwargs)  
        context['search_info'] = 'Search: "{}"'.format(self.kwargs['q'])
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'easygo_review/post_detail1.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_count'] = Post.objects.all().count()
        context['comment_form'] = CommentForm()

        email = self.request.session.get('email', None)
        context['email'] = email

        authenticated_post = get_authenticated_post(self.request)
        context['authenticated_post'] = authenticated_post 

        if email:
            blog_post = BlogPost.objects.filter(email=email).first()  
            if blog_post:
                user_name = blog_post.name
                context['user_name'] = user_name
            else:
                context['user_name'] = None
        else:
            context['user_name'] = None

        return context
        

class PostUpdate(UpdateView):
    model = Post
    template_name = 'easygo_review/post_form.html'
    fields = ['content', 'rating']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        email = self.request.session.get('email', None)
        context['email'] = email

        authenticated_post = get_authenticated_post(self.request)
        context['authenticated_post'] = authenticated_post 

        if email:
            blog_post = BlogPost.objects.filter(email=email).first()  
            if blog_post:
                user_name = blog_post.name
                context['user_name'] = user_name
            else:
                context['user_name'] = None
        else:
            context['user_name'] = None

        return context
    

class CommentCreate(View):
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        email = request.session.get('email', None)

        user_name = None
        if email:
            blog_post = BlogPost.objects.filter(email=email).first()
            if blog_post:
                user_name = blog_post.name

        comment_form = CommentForm()
        
        context = {
            'post': post,
            'email': email,
            'user_name': user_name,
            'comment_form': comment_form,
        }

        return render(request, 'easygo_review/post_detail1.html', context)

    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        email = request.session.get('email', None)

        user_name = None
        if email:
            blog_post = BlogPost.objects.filter(email=email).first()
            if blog_post:
                user_name = blog_post.name

        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = user_name
            comment.save()
            return redirect(post.get_absolute_url())  # Redirect to post detail page

        # Render the form with errors if form is not valid
        context = {
            'post': post,
            'email': email,
            'user_name': user_name,
            'comment_form': comment_form,
        }
        return render(request, 'easygo_review/post_detail1.html', context)
    

class CommentUpdate(UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'easygo_review/comment_form.html'

    def get_object(self, queryset=None):
        comment = super().get_object(queryset)        
        email = self.request.session.get('email', None)
        user_name = None

        if email:
            blog_post = BlogPost.objects.filter(email=email).first()
            if blog_post:
                user_name = blog_post.name

        if comment.author != user_name:
            raise PermissionDenied('No right to edit')

        return comment
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        email = self.request.session.get('email', None)
        user_name = None

        if email:
            blog_post = BlogPost.objects.filter(email=email).first()
            if blog_post:
                user_name = blog_post.name

        context['email'] = email
        context['user_name'] = user_name
        return context

    def get_success_url(self):
        post = self.get_object().post
        return post.get_absolute_url() + '#comment-list'


class CommentDelete(DeleteView):
    model = Comment
    template_name = 'easygo_review/comment_confirm_delete.html'

    def get_object(self, queryset=None):
        comment = super().get_object(queryset)        
        email = self.request.session.get('email', None)
        user_name = None

        if email:
            blog_post = BlogPost.objects.filter(email=email).first()
            if blog_post:
                user_name = blog_post.name

        if comment.author != user_name:
            raise PermissionDenied('No right to delete Comment')

        return comment
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        email = self.request.session.get('email', None)
        user_name = None

        if email:
            blog_post = BlogPost.objects.filter(email=email).first()
            if blog_post:
                user_name = blog_post.name

        context['email'] = email
        context['user_name'] = user_name
        return context

    def get_success_url(self):
        post = self.get_object().post
        return post.get_absolute_url() + '#comment-list'
    

def index(request):
    posts = Post.objects.all()

easygo_review/templates/easygo_review/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en-us">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Reviews for EasyGo Airport Shuttle{% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'basecamp/favi/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="google-site-verification" content="hae39L0Kv7JIxVc3YclvckH7Im5SdYa2hk_vZbGJIkA" />
    <!-- SEO Meta Tags-->
    <meta name="description" content="EasyGo airport shuttle bus provide Sydney airport transport service, private ride with the cheap price. ">
    <meta name="keywords" content="EasyGo reviews, EasyGo Airport Shuttle Reviews, reviews for easygo shuttle, reviews for easygo airport transfers">
    <meta name="author" content="easycoding.live">
    <link rel="stylesheet" href="{% static 'easygo_review/css/bootstrap.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'easygo_review/css/custom.min.css' %}">
    <link rel="stylesheet" href="{% static 'easygo_review/css/styles.css' %}">
</head>
<body>
{% include 'easygo_review/navbar.html' %}

<div class="container">
    <div class="row">
        <!-- easygo_review Entries Column -->        
            {% block content %}
            {% endblock %}            
    </div>
</div>
<!-- footer -->    
<div class="container" style="margin-top: 80px; padding: 0;">
    <div class="footer container-xl width-full p-responsive" role="contentinfo" style="padding-right: 10px;">
        <ul class="list-style-none border-top d-flex justify-content-end">
            <li class="mr-3 mr-lg-2 list-unstyled"><small><a href="#">2024 All rights reserved by EasyGo Airport Shuttle</a></small></li>                    
        </ul>
    </div>
</div>
<script>
    function search_post() {
        var search_value = document.getElementById('search-input').value;    
        if (search_value.trim() === "") {
            alert("Please enter a valid search term.");
        } else {
            location.href = "/easygo_review/search/" + encodeURIComponent(search_value) + "/";
        }
    }    
    function wait_for_enterkey() {
        if (window.event.keyCode == 13) {
            search_post();
        }
    }
</script>
<script src="{% static 'easygo_review/js/jquery.min.js' %}"></script>
<script src="{% static 'easygo_review/js/bootstrap.min.js' %}"></script>
<script src="https://www.google.com/recaptcha/api.js?render={{ RECAPTCHA_V3_SITE_KEY }}" defer></script>
    <script>
        grecaptcha.ready(function() {
            grecaptcha.execute("{{ RECAPTCHA_V3_SITE_KEY }}", {action: 'homepage'}).then(function(token) {
                const csrftoken = '{{ csrf_token }}';
                fetch('/recaptcha-verify/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken
                    },
                    body: JSON.stringify({recaptchaToken: token})
                }).then(response => {
                    return response.json();
                }).then(data => {
                    if (data.success) {
                        console.log('reCAPTCHA validation succeeded');
                    } else {
                        console.log('reCAPTCHA validation failed:', data.message);
                    }
                });
            });
        });
    </script>
</body>
</html>

easygo_review/templates/easygo_review/base_sub.html
<!DOCTYPE html>
{% load static %}
<html lang="en-us">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}View more suburbs for EasyGo Airport Shuttle{% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'basecamp/favi/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="google-site-verification" content="hae39L0Kv7JIxVc3YclvckH7Im5SdYa2hk_vZbGJIkA" />
    <!-- SEO Meta Tags-->
    <meta name="description" content="This is the review page for people who have used our EasyGo Airport Shuttle service">
    <meta name="keywords" content="reviews easygo shuttle, reviews easygo, reviews for easygo airport shuttle, customer reviews for easygo service">
    <meta name="author" content="EasyGo Airport Shuttle">
    <link rel="stylesheet" href="{% static 'easygo_review/css/bootstrap.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'easygo_review/css/custom.min.css' %}"> 
</head>
<body>

{% include 'easygo_review/navbar_sub.html' %}

<div class="container">
    <div class="row">
        <!-- easygo_review Entries Column -->
        
            {% block content %}
            {% endblock %}    
        
    </div>
</div>

<!-- footer -->    
<div class="container" style="margin-top: 80px; padding: 0;">
    <div class="footer container-xl width-full p-responsive" role="contentinfo" style="padding-right: 10px;">
        <ul class="list-style-none border-top d-flex justify-content-end">
            <li class="mr-3 mr-lg-2 list-unstyled"><small><a href="#">2024 All rights reserved by EasyGo Airport Shuttle</a></small></li>                    
        </ul>
    </div>
</div>
<script src="{% static 'easygo_review/js/jquery.min.js' %}"></script>
<script src="{% static 'easygo_review/js/bootstrap.min.js' %}"></script>

</body>
</html>

easygo_review/templates/easygo_review/comment_confirm_delete.html
{% extends 'easygo_review/base.html' %}

{% block title %} Confirm Deletion {% endblock %}

{% block content %}
    <h3>Delete Comment: </h3>
    <hr/>
    <form method="post">{% csrf_token %}
        {{ object.get_markdown_content | safe }}
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>

    {{ form.media }}
{% endblock %}

easygo_review/templates/easygo_review/comment_form.html
{% extends 'easygo_review/base.html' %}

{% block title %} EasyGo Reveiws {% endblock %}

{% block content %}
    <h3>Edit Comment: </h3>
    <hr/>
    <form method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>

    {{ form.media }}
{% endblock %}

easygo_review/templates/easygo_review/custom_login.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Log In" %}{% endblock %}

{% block content %}
<style>
    form {
        margin-top: 40px; /* 상단 마진을 40px로 설정 */
    }
</style>
<section class="bg-dark position-relative pt-6 pb-5 py-sm-6">
    <div class="position-absolute top-0 start-0 w-100 h-100 bg-size-cover" ></div>
        <div class="position-relative zindex-5 container pb-3 pt-sm-2">
          <div class="mx-auto" style="max-width: 460px;">
            <h3 class="text-light text-center pt-sm-2">{% trans "Sign In" %}</h3><br>
            <form class="login text-light text-center mb-4" method="POST" action="{% url 'easygo_review:custom_login' %}">
                {% csrf_token %}
                <label for="email">{% trans "Email" %}</label><br>
                <input type="email" id="email" name="email" required><br><br><br>
                <button class="primaryAction btn btn-warning" type="submit">{% trans "Sign In" %}</button>
                <br><br>
                {% if error %}
                    <p style="color: red;"><large>{{ error }}</large></p>
                {% endif %}
            </form>
            
</section>
{% endblock %}

easygo_review/templates/easygo_review/custom_logout.html
{% extends "easygo_review/base.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
<style>
    form {
        margin-top: 40px; /* 상단 마진을 40px로 설정 */
    }
</style>
<section class="bg-dark position-relative pt-6 pb-5 py-sm-6">
    <div class="position-absolute top-0 start-0 w-100 h-100 bg-size-cover" ></div>
        <div class="position-relative zindex-5 container pb-3 pt-sm-2">
          <div class="mx-auto" style="max-width: 460px;">
            <h3 class="text-light text-center pt-sm-2" style="padding-top: 30px;">{% trans "Sign Out" %}</h3><br>
            <form class="login text-light text-center mb-4" method="POST" action="{% url 'easygo_review:logout' %}">
                {% csrf_token %}
                {{ form.logout }}<br><br>                
                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}<br>
                <button class="primaryAction btn btn-warning" type="submit">{% trans "Sign Out" %}</button>
            </form>
            
</section>
{% endblock %}

easygo_review/templates/easygo_review/navbar.html
<div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary" id="navbar">
    <div class="container">
        <div class="navbar-brand" style="margin-left: 0;">
            <a href="/home/"><i class="fad fa-layer-group"></i></a>
            <button class="navbar-toggler ms-n2 me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#primaryMenu"><span class="navbar-toggler-icon"></span></button><a class="navbar-brand flex-shrink-0 order-lg-1 mx-auto ms-lg-0 pe-lg-2 me-lg-4" href="/home/"><img class="navbar-floating-logo d-none d-lg-block" src="/static/basecamp/images/easygo_icon.webp" style="border-radius: 30%" alt="EasyGo_image" width="40"></a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">    
                <li class="nav-item">
                    <a class="nav-link" href="/home/">Home</a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" href="/easygo_review/">Reivews</a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" href="/more_suburbs/">Suburbs</a>
                </li>                 
            </ul>

            <ul class="nav navbar-nav ml-auto">                
                {% if email %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">{{ user_name }} <span class="caret"></span></a>
                        <div class="dropdown-menu" aria-labelledby="download">                            
                            <a class="dropdown-item" href="/easygo_review/custom_logout">Log out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">
                            Log in
                        </button>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</div>

{% load socialaccount %}

<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Please Log in</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <a role="button" class="btn btn-outline-danger" href="{% provider_login_url 'google' %}"><i class="fab fa-google"></i>  Log in with Google</a>
                    </div>
                    <div class="col-md-6">
                        <a role="button" class="btn btn-outline-info" href="{% url 'easygo_review:custom_login' %}"><i class="fas fa-envelope"></i>  Log in with Email</a>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

easygo_review/templates/easygo_review/post_detail1.html
{% extends 'easygo_review/base.html' %}

{% block title %}EasyGo Reivew{% endblock %}

{% block content %}
<div class="review-section" style="padding: 20px;">  
    <br/> 
    <!-- Author -->
    <div class="low" style="display: flex; align-items: center;">
        <div>
            <p class="lead">
                Review by
                <a href="#">{{ object.name }}</a>
            </p>
            <p>posted on {{ object.date }}</p>
        </div>
        
        {% if user_name == object.name %}
            <button type="button" class="btn btn-primary" style="margin-left: auto;" onclick="location.href='{{ object.get_update_url }}'">EDIT REVIEW</button>
        {% endif %}
    </div>
    <br/>    
    <!-- Post Content -->
    {{ object.get_markdown_content | safe }}

    <hr>

    <!-- Comments Form -->
    <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
            {% if not email %}
            <button type="button" class="btn btn-outline-dark btn-block" data-toggle="modal" data-target="#loginModal">
                Log in
            </button>            
            {% else %}
            <form method="post" action="{{ object.get_absolute_url }}new_comment/">{% csrf_token %}
                <div class="form-group">
                    {{ comment_form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary btn-sm float-right">Submit Comment</button>                
            </form>
            {% endif %}
        </div>
    </div>

    <div id="comment-list">
        {% for comment in object.comment_set.all %}
            <div class="media mb-4" id="comment-id-{{ comment.pk }}">                
                <div class="media-body">
                    {% if comment.author == user_name %}
                        <button class="btn btn-sm btn-info float-right" onclick="location.href='/easygo_review/comment/{{ comment.pk }}/update/'">edit</button>
                        <button class="btn btn-sm btn-warning float-right" data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">delete</button>
                    {% endif %}
                    <h5 class="mt-0">{{ comment.author }} <small class="text-muted">{{ comment.created_at }}</small></h5>
                    {{ comment.get_markdown_content | safe }}
                </div>
            </div>
        {% endfor %}
    </div>

    {% for comment in object.comment_set.all %}
        {% if user_name == comment.author %}
            <!-- Modal -->
            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete the comments?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>{{ comment.get_markdown_content | safe  }}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" onclick="location.href='/easygo_review/comment/{{ comment.pk }}/delete/'">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}